square_config:
  total_cards: 15
  concurrency: 4
  sleepy_time: 2
set_params:
  set: "Null Revelation"
  themes:
    - "No cards in hand"
    - "Emptiness and void"
    - "Forgotten Echoes"
    - "Oblivion Cult"
    - "Ascetic Wanderers"
    - "Solitude"
    - "The silence after the storm has passed, when only memories remain"
    - "Echoes of a world lost to time, where nothing remains but dust"
    - "Stillness"
    - "The last candle flickering in endless darkness"

api_params:
  generate_image_prompt: false
  creative: false
  include_explanation: false
  image_model: "dall-e-2" # options: dall-e-2, dall-e-3, none
  model: "gpt-41"


mtgcg_mse_config:
  image_method: "localSD" # options: none, localSD, download

skeleton_params:
  types_mode: normal
  power_level: 7.5 # Power level of the card, 1-10 or None
  wildcard_supertype: false
  fixed_amount_themes: 0 # if not zero, will select a fixed amount of themes from the available ones instead of mutating them randomly
  mutation_chance_per_theme: 12.5 # Chance to mutate each theme, ignored if fixed_amount_themes is not zero
  colors: ["white", "red", "colorless"]
  colors_weights:
    white: 45
    red: 45
    colorless: 10
  card_types_weights:
    _default:
      kindred: 0
    white:
      land: 5
      basic land: 5
  function_tags:
    ramp or mana fixing: 15
    draw or card advantage: 5
    removal or control: 10
    No cards in hand payoff: 20
    Discard to gain benefit: 15
    If discarded, gain benefit: 20
    Discard Synergy: 10
    impulse draw: 15
    board wipe or mass removal: 5
    activated ability: 5
    Flying or other evasion: 5
    simple or straightforward: 10
  tags_maximum: 2 # Default is null, which means no limit

SD_config:
  model_swap_chance: 100
  special_tags:
    Comic Hard Cell Shade: 
      weight: 2.5
      chance: 100