square_config:
  total_cards: 60
  concurrency: 1
  sleepy_time: 0.5
set_params:
  set: "Goblin Road Rage"
  themes:
    - "Goblin vehicles"
    - "Mad Max chaos"
    - "Scrap metal machines"
    - "Desert raiders"
    - "Explosive mayhem"
    - "Ramshackle convoys"
    - "Speed and recklessness"
    - "Jury-rigged engines"
    - "Wasteland survival"
    - "Tribal goblin gangs"

api_params:
  image_model: "none" # options: dall-e-2, dall-e-3, none
  model: "gpt-41"


mtgcg_mse_config:
  image_method: "localSD" # options: none, localSD, download

skeleton_params:
  types_mode: play # normal | play
  power_level: 8
  standard_deviation_powerLevel: 0.5
  power_level_rarity_skew: 0.2
  wildcard_supertype: true
  fixed_amount_themes: 2 # if not zero, will select a fixed amount of themes from the available ones instead of mutating them randomly
  mutation_chance_per_theme: 12.5 # Chance to mutate each theme, ignored if fixed_amount_themes is not zero
  colors: ["red", "black", "green", "colorless"]
  colors_weights:
    red: 40
    black: 25
    green: 25
    colorless: 10
  card_types:
    - "creature"
    - "artifact creature"
    - "planeswalker"
    - "instant"
    - "sorcery"
    - "enchantment"
    - "saga"
    - "battle"
    - "land"
    - "basic land"
    - "artifact"
    - "kindred"
    - "artifact creature vehicle"
  card_types_color_weights:
    _all:
      "artifact creature vehicle": 10
    colorless:
      "artifact creature vehicle": 30
  function_tags:
    ramp or mana fixing: 15
    draw or card advantage: 5
    removal or control: 10
    pilot: 15
    speed: 20
    speed counter: 20
    vehicle: 15
    board wipe or mass removal: 5
    activated ability: 5
    Flying or other evasion: 5
    simple or straightforward: 10
  tags_maximum: 3 # Default is null, which means no limit